# Generated by Django 6.0.6 on 2026-07-01 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='scheduling.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('modality', models.CharField(choices=[('f2f', 'Face-to-face'), ('blended', 'Blended'), ('online', 'Online')], default='f2f', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='campus.room')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('absent', 'Absent')], default='scheduled', max_length=10)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('checkin_method', models.CharField(blank=True, choices=[('qr_scan', 'QR scan'), ('manual_code', 'Manual code'), ('online_manual', 'Online (manual)'), ('force_handover', 'Force handover')], max_length=15)),
                ('declared_modality', models.CharField(blank=True, choices=[('f2f', 'Face-to-face'), ('blended', 'Blended'), ('online', 'Online')], max_length=10)),
                ('modality_changed_at', models.DateTimeField(blank=True, null=True)),
                ('teams_link', models.URLField(blank=True)),
                ('ended_early', models.BooleanField(default=False)),
                ('early_end_reason', models.CharField(blank=True, max_length=255)),
                ('room_released_at', models.DateTimeField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('handover_from_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_to', to='scheduling.session')),
                ('modality_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modality_changes', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='campus.room')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling.schedule')),
            ],
            options={
                'ordering': ['-date', 'scheduled_start'],
                'indexes': [models.Index(fields=['date', 'status'], name='scheduling__date_f4b818_idx'), models.Index(fields=['room', 'date'], name='scheduling__room_id_91a2db_idx')],
            },
        ),
    ]
