# Generated by Django 6.0.6 on 2026-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_modality_shift_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='checkin_method',
            field=models.CharField(blank=True, choices=[('qr_scan', 'QR scan'), ('manual_code', 'Manual code'), ('online_manual', 'Online (manual)'), ('force_handover', 'Force handover'), ('merged', 'Merged (sibling fill)')], max_length=15),
        ),
    ]
