# Generated by Django 6.0.6 on 2026-07-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_session_checkin_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10),
        ),
    ]
