# Generated by Django 6.0.6 on 2026-07-22

from django.db import migrations, models
from django.db.models import Q


DRAFT = "draft"
ACTIVE = "active"
ARCHIVED = "archived"


def _term_label(row):
    return (
        f"id={row['id']} name={row['name']!r} "
        f"dates={row['start_date']}..{row['end_date']}"
    )


def forwards(apps, schema_editor):
    AcademicTerm = apps.get_model("scheduling", "AcademicTerm")
    rows = list(
        AcademicTerm.objects
        .order_by("id")
        .values("id", "name", "start_date", "end_date", "is_active")
    )

    active_rows = [row for row in rows if row["is_active"]]
    if len(active_rows) > 1:
        names = ", ".join(_term_label(row) for row in active_rows)
        raise RuntimeError(f"More than one active AcademicTerm row: {names}")

    seen_names = {}
    for row in rows:
        key = (row["name"] or "").casefold()
        if key in seen_names:
            first = seen_names[key]
            raise RuntimeError(
                "Duplicate AcademicTerm names under database comparison rules: "
                f"{_term_label(first)} and {_term_label(row)}"
            )
        seen_names[key] = row

    for row in rows:
        if row["end_date"] < row["start_date"]:
            raise RuntimeError(
                "Invalid AcademicTerm date order before lifecycle migration: "
                f"{_term_label(row)}"
            )

    for index, left in enumerate(rows):
        for right in rows[index + 1:]:
            overlaps = (
                left["start_date"] <= right["end_date"]
                and left["end_date"] >= right["start_date"]
            )
            if overlaps:
                raise RuntimeError(
                    "Inclusive AcademicTerm date overlap before lifecycle "
                    f"migration: {_term_label(left)} overlaps {_term_label(right)}"
                )

    for row in rows:
        status = ACTIVE if row["is_active"] else ARCHIVED
        AcademicTerm.objects.filter(pk=row["id"]).update(status=status)


def backwards(apps, schema_editor):
    AcademicTerm = apps.get_model("scheduling", "AcademicTerm")
    AcademicTerm.objects.update(is_active=False)
    AcademicTerm.objects.filter(status=ACTIVE).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0007_class_suspension_and_cancelled_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicterm",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    (DRAFT, "Draft"),
                    (ACTIVE, "Active"),
                    (ARCHIVED, "Archived"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="academicterm",
            name="status",
            field=models.CharField(
                choices=[
                    (DRAFT, "Draft"),
                    (ACTIVE, "Active"),
                    (ARCHIVED, "Archived"),
                ],
                default=DRAFT,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="academicterm",
            name="name",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AddConstraint(
            model_name="academicterm",
            constraint=models.CheckConstraint(
                condition=Q(end_date__gte=models.F("start_date")),
                name="term_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicterm",
            constraint=models.UniqueConstraint(
                condition=Q(status=ACTIVE),
                fields=("status",),
                name="uniq_active_academic_term",
            ),
        ),
        migrations.RemoveField(
            model_name="academicterm",
            name="is_active",
        ),
    ]
