# Generated by Django 6.0.6 on 2026-07-01 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('checker', 'Checker'), ('guard', 'Guard')], max_length=10)),
                ('type', models.CharField(choices=[('shift', 'Shift'), ('standing', 'Standing posting')], max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('floors', models.ManyToManyField(related_name='assignments', to='campus.floor')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='scheduling.academicterm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckerValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verified', 'Verified'), ('flag_identity_mismatch', 'Flag: identity mismatch'), ('flag_not_present', 'Flag: not present'), ('confirmed_absent', 'Confirmed absent'), ('confirmed_empty', 'Confirmed empty'), ('verified_empty', 'Verified empty')], max_length=25)),
                ('identity_match', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('offline_queued', models.BooleanField(default=False)),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to='campus.room')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='scheduling.session')),
            ],
            options={
                'ordering': ['-validated_at'],
            },
        ),
    ]
