"""Pure campus-domain helpers. No HTTP, no cross-app module-level imports.

`campus` is the lowest app in the dependency order — `scheduling`, `ops` and
`verification` all import FROM it. Nothing here may import back UP, so every
relation this module inspects is reached through a REVERSE ACCESSOR on a Room
instance rather than by importing the referencing model.
"""


def room_delete_blockers(room):
    """Return {relation_name: count} for every relation that blocks deleting `room`.

    Only NON-ZERO entries are included, so an empty dict means the room is
    genuinely unreferenced and safe to delete (IFO-01b / D-17). The caller
    renders the keys to NAME what is blocking, which is why this returns data
    rather than raising.

    FIVE relations are counted — D-17 named three, D-20 added the fourth, and
    the fifth is the one no decision named:

      schedules     Schedule.room          PROTECT
      sessions      Session.room           PROTECT
      bookings      Booking.room           PROTECT (as of D-19; was CASCADE)
      validations   CheckerValidation.room PROTECT
      reservations  ModalityShiftItem.assigned_room   SET_NULL  <-- see below

    **Why `reservations` is load-bearing and not merely thorough.**
    The first four are PROTECT, so the database would refuse those deletes even
    if this probe did not exist — the probe only upgrades a ProtectedError 500
    into a named refusal. `assigned_room` is different in kind. It is the room
    RESERVED at Dean approval (D-18), and `ops.availability.room_is_free()`
    already counts it as real occupancy (D-08) — but the FK is SET_NULL, so the
    database will NOT refuse the delete. It succeeds, and silently nulls a live
    approved reservation. That is precisely the silent-destruction failure D-19
    was written to close, one relation over, and THIS PROBE IS THE ONLY CONTROL
    THAT CATCHES IT. Removing it re-opens the hole with no test or constraint
    to notice.

    **All bookings count, not just status="active" (D-19).**
    D-10 treats a cancelled booking as not occupying the room for AVAILABILITY
    purposes, but availability and deletability are different questions. A
    cancelled booking is still historical data that the pre-D-19 CASCADE would
    have destroyed, so "referenced by any Booking" is read conservatively here.

    **Two Room relations are deliberately EXCLUDED.** Recorded so a later reader
    finding them does not assume they were overlooked:

      - `modality_preferred_items` (`preferred_room`, SET_NULL) — a faculty
        PREFERENCE is not a reservation. The server re-resolves the room at
        approval (D-18), so a preference pointing at a deleted room is
        meaningless, not lost data.
      - `conflict_flags` (`ops.RoomConflictFlag.room`, CASCADE) — DERIVED state.
        A flag is generated from contradictory occupancy; a room with no
        schedules/sessions/bookings has none by construction, and any stale flag
        is regenerated by the next sweep. Cascading it away destroys nothing
        that is not reproducible.

    **Three rejected alternatives**, so this does not get "improved" into
    something worse:

      - `django.contrib.admin.utils.NestedObjects` — an undocumented admin
        internal that LOADS thousands of model instances to answer what is
        fundamentally a yes/no question.
      - `django.db.models.deletion.Collector` — resolves the entire deletion
        graph and signals blockers by RAISING, i.e. exception-driven control
        flow for a question the UI needs as data. It also would not report
        `assigned_room` as a blocker at all, since SET_NULL is not a block.
      - Five scalar COUNT queries on indexed FK columns — chosen. Cheap, build
        no parameter list (MSSQL 2100-param safe), and return exactly the shape
        the UI needs to name each blocker.
    """
    counts = {
        "schedules": room.schedules.count(),
        "sessions": room.sessions.count(),
        "bookings": room.bookings.count(),
        "validations": room.validations.count(),
        "reservations": room.modality_assigned_items.count(),
    }
    return {relation: n for relation, n in counts.items() if n}


def floor_delete_blockers(floor):
    """Return {relation: count} for what blocks deleting `floor` (Phase 10).

    Floor -> Room is PROTECT, so a floor holding rooms cannot be deleted. Deleting
    a room is itself a guarded, named act (`room_delete_blockers`), so the campus
    structure is torn down bottom-up: rooms, then the floor, then the building.
    Only non-zero entries are returned; an empty dict means the floor is safe to
    delete.
    """
    counts = {"rooms": floor.rooms.count()}
    return {relation: n for relation, n in counts.items() if n}


def building_delete_blockers(building):
    """Return {relation: count} for what blocks deleting `building` (Phase 10).

    Building -> Floor is CASCADE and Floor -> Room is PROTECT, so a building whose
    floors hold rooms cannot be deleted (the cascade hits the PROTECT). Rather than
    rely on that indirect refusal, this names both what is under the building
    (floors) and what ultimately blocks it (rooms), and requires the operator to
    empty it first -- the same bottom-up, no-silent-loss discipline as
    `room_delete_blockers`. A building with floors but no rooms is still reported
    (``floors``) so a delete never silently cascades away floor rows an operator
    forgot were there. Only non-zero entries are returned.
    """
    # Local import keeps this module free of module-level imports (its stated
    # contract); Room is same-app, so this is not an upward dependency.
    from campus.models import Room
    counts = {
        "floors": building.floors.count(),
        "rooms": Room.objects.filter(floor__building=building).count(),
    }
    return {relation: n for relation, n in counts.items() if n}
