# Generated by Django 6.0.6 on 2026-07-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_cs_collation_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='out_of_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='out_of_service_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
