# Generated by Django 6.0.6 on 2026-07-02 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_cs_collation_tokens'),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomConflictFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_key', models.CharField(max_length=120)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_flags', to='campus.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('conflict_key',), name='uniq_open_conflict_per_key')],
            },
        ),
    ]
