# Generated by Django 6.0.6 on 2026-07-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_roomconflictflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_affected', models.IntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_name', '-started_at'], name='ops_jobrun_job_nam_390546_idx')],
            },
        ),
    ]
