# Generated by Django 6.0.6 on 2026-07-22

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models


def _candidate_term_ids(AcademicTerm, week_start):
    week_end = week_start + timedelta(days=6)
    return list(
        AcademicTerm.objects.filter(
            start_date__lte=week_end,
            end_date__gte=week_start,
        )
        .order_by("id")
        .values_list("id", flat=True)
    )


def backfill_weekly_report_terms(apps, schema_editor):
    AcademicTerm = apps.get_model("scheduling", "AcademicTerm")
    WeeklyReport = apps.get_model("ops", "WeeklyReport")
    reports = list(
        WeeklyReport.objects.order_by("id").values("id", "week_start")
    )

    for report in reports:
        candidates = _candidate_term_ids(AcademicTerm, report["week_start"])
        if len(candidates) != 1:
            raise RuntimeError(
                f"WeeklyReport {report['id']} week {report['week_start']} has "
                f"{len(candidates)} candidate terms: {candidates}"
            )
        WeeklyReport.objects.filter(pk=report["id"]).update(term_id=candidates[0])


def clear_weekly_report_terms(apps, schema_editor):
    WeeklyReport = apps.get_model("ops", "WeeklyReport")
    WeeklyReport.objects.update(term_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0005_booking_protect_import_staging"),
        ("scheduling", "0008_term_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="importstaging",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_stagings",
                to="scheduling.academicterm",
            ),
        ),
        migrations.AddField(
            model_name="weeklyreport",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="weekly_reports",
                to="scheduling.academicterm",
            ),
        ),
        migrations.RunPython(
            backfill_weekly_report_terms,
            clear_weekly_report_terms,
        ),
        migrations.AlterUniqueTogether(
            name="weeklyreport",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="weeklyreport",
            constraint=models.UniqueConstraint(
                fields=("term", "week_start", "department"),
                name="uniq_weekly_report_term_week_department",
            ),
        ),
        migrations.AlterField(
            model_name="weeklyreport",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="weekly_reports",
                to="scheduling.academicterm",
            ),
        ),
    ]
